exports.mongoUrl = process.env.W3_MONGO_URL;
exports.mongoPoolSize = +(process.env.W3_MONGO_POOL_SIZE || 5);
exports.maxQueryLimit = +(process.env.W3_MAX_QUERY_LIMIT || 200);
exports.maxMessageSize = +(process.env.W3_MAX_MESSAGE_SIZE || 140);
exports.maxQuerySize = +(process.env.W3_MAX_QUERY_SIZE || 1024);
exports.twitterConsumerKey = process.env.W3_TWITTER_CONSUMER_KEY || '8slh21QmwgnRXq2ukNNng';
exports.twitterConsumerSecret = process.env.W3_TWITTER_CONSUMER_SECRET;
exports.sessionSecret = exports.twitterConsumerSecret;
exports.betaUsers = process.env.W3_BETA_USERS ? process.env.W3_BETA_USERS.split(',') : [ 'tjanczuk', 'ccaldato' ];
